name: CICD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      pull-requests: read/write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      
      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup CDK
        run: |
          npm install -g aws-cdk
          cdk --version
          cdk bootstrap

      - name: Setup CDK dependencies
        run: |
          pip install -r requirements-dev.txt
          pip list

      - name: Setup Layer dependencies
        run: |
          mkdir -p layer/python
          pip install -r requirements.txt -t layer/python
          pip list
          find layer/python -type f | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm

      - name: CDK Diff Check
        run: |
          cdk diff --no-path-metadata --no-asset-metadata 2>&1 | tee ./comments
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
      
      - name: Post comments
        if: contains(github.event_name, 'pull_request')
        run: |
          gh pr comment -F ./comments "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: cdk deploy --no-path-metadata --no-asset-metadata
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'

      - name: Upload cdk.out
        if: contains(github.event_name, 'push')
        run: |
          uuid=`uuidgen`
          echo ${uuid} > ./uuid
          stack=`cdk ls 2>&1 | tr -d "\n"`
          aws s3 cp ./cdk.out/ s3://${CDK_OUT_UPLOAD_BUCKET}/${stack}/${uuid}/ --recursive --exclude "*" --include "*.json"
          aws s3 cp ./uuid s3://${CDK_OUT_UPLOAD_BUCKET}/${stack}/
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          CDK_OUT_UPLOAD_BUCKET: ${{ secrets.CDK_OUT_UPLOAD_BUCKET }}
